[versions]
kotlin = "1.8.22"
kotlinx-json = "1.5.1"
kotlinx-coroutines = "1.7.3"

junit5 = "5.8.2"
crowdin = "1.0.2-SNAPSHOT"
ustats = "1.0.2"
universalcraft = "277"
bstats = "3.0.2"
crosslib = "1.0.0-SNAPSHOT"

opus-jni = "1.0.0"
opus-concentus = "acaadf2075"
rnnoise-jni = "1.0.0"

[libraries]
lombok       = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations  = { module = "org.jetbrains:annotations", version = "23.0.0" }
guava        = { module = "com.google.guava:guava", version = "31.1-jre" }
gson         = { module = "com.google.code.gson:gson", version = "2.9.0" }

slf4j        = { module = "org.slf4j:slf4j-api", version = "1.7.30" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "1.7.30" }
junit-api    = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
opus-jni     = { module = "com.plasmoverse:opus-jni-rust", version.ref = "opus-jni" }
opus-concentus = { module = "com.github.lostromb.concentus:Concentus", version.ref = "opus-concentus" }
rnnoise-jni  = { module = "com.plasmoverse:rnnoise-jni-rust", version.ref = "rnnoise-jni" }
netty        = { module = "io.netty:netty-all", version = "4.1.77.Final"}
config       = { module = "su.plo.config:config", version = "1.0.1" }
luckperms    = { module = "net.luckperms:api", version = "5.4" }

guice        = { module = "com.google.inject:guice", version = "5.0.1" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
aopalliance  = { module = "aopalliance:aopalliance", version = "1.0" }

kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

crowdin-lib = { module = "su.plo.crowdin:lib", version.ref = "crowdin" }

[plugins]
architectury-plugin = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
architectury-loom   = { id = "dev.architectury.loom", version = "0.12.0-SNAPSHOT" }
shadow              = { id = "com.github.johnrengelman.shadow", version = "7.1.0" }
idea-ext            = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7"}
crowdin-plugin      = { id = "su.plo.crowdin.plugin", version.ref = "crowdin" }
