modLoader="javafml"
loaderVersion="${forgeVersion}"
license="LGPL-3.0"
issueTrackerURL="https://github.com/plasmoapp/plasmo-voice/issues"
[[mods]]
modId="plasmovoice"
version="${version}"
displayName="Plasmo Voice"
displayURL="https://github.com/plasmoapp/plasmo-voice"
logoFile="icon.png"
authors="Apehum"
description="A proximity voice chat mod with audio positioning and lots of features"
[[dependencies.plasmovoice]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersion}"
    ordering="NONE"
    side="BOTH"
[[dependencies.plasmovoice]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersions}"
    ordering="NONE"
    side="BOTH"
