name: Publish

on:
  push:
    branches:
      - v2.1.x

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          16
          17
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --stacktrace -Psnapshot=true

    - name: Publish to snapshots maven repository
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish --stacktrace -Psnapshot=true

    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: true
        github-prerelease: true
