name: Publish

on:
  push:
    branches:
      - v2.0.x-release

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Build Dokka with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dokkaHtmlCollector

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./build/dokka/htmlCollector

    - name: Publish Paper to Modrinth
      uses: Apehum/mc-publish@v1.1
      with:
        name: 'Plasmo Voice'
        split-releases: true
        files-primary: build/libs/*-@(Paper)-*.jar
        version-resolver: 'exact'

        changelog-file: server/changelog.md

        game-versions: |
          1.19.2
          1.19.3
          1.19.4

        modrinth-unfeature-mode: 'subset'
        modrinth-id: 1bZhdhsH
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

    - name: Publish Bungee/Velocity to Modrinth
      uses: Apehum/mc-publish@v1.1
      with:
        name: 'Plasmo Voice'
        split-releases: true
        files-primary: build/libs/*-@(BungeeCord|Velocity)-*.jar
        version-resolver: 'exact'

        changelog-file: proxy/changelog.md

        game-versions: |
          1.19.2
          1.19.3
          1.19.4

        modrinth-unfeature-mode: 'subset'
        modrinth-id: 1bZhdhsH
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

    - name: Publish Client to Modrinth/CurseForge
      uses: Apehum/mc-publish@v1.1
      with:
        name: 'Plasmo Voice'
        split-releases: true
        files-primary: build/libs/*-@(forge|fabric)-*.jar
        version-resolver: 'exact'

        changelog-file: client/changelog.md

        modrinth-unfeature-mode: 'subset'
        modrinth-id: 1bZhdhsH
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 467028
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        
    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false

  deploy-dokka:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages-release
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
